(** Html output module, does the translation vdoc -> html *)

open Vdoc
open Printf
open Cst

exception Unhandled_case


let initialize () = ()

let header title =
  (*FIXME: add title and charset *)
  "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n"              ^
  "\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"                  ^
  "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n"                   ^
  "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf8\"/>\n" ^
  "<link href=\"coqdoc.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"        ^
  "<title>"^ title ^ "</title>\n</head>\n\n"                                  ^
  "<body>\n\n<div id=\"page\">\n\n<div id=\"header\">\n</div>\n\n"            ^
  "<div id=\"main\">\n\n" ^
  "<h1>" ^ title ^ "</h1>\n<hr/>\n\n"

let rec print_with_sep sep = function
  [] -> ""
  | [e] -> e
  | e::l -> sprintf "%s%s%s" e sep (print_with_sep sep l)

let pr_raw raw =
  if raw.html <> "" then raw.html
  else raw.default

let replace_newlines str = Str.global_replace (Str.regexp "\n") "<br/>\n" str

(* Handle syntactic coloration of code pieces *)
let doc cst =
  let print_flat_element = function
    `Vernac s          -> sprintf"[%s]" s
    | `Pretty_print s  -> sprintf "[[%s]]" s
    | `Section (lvl,s) -> sprintf "<h%d class=\"section\">%s</h%d>" lvl s lvl
    | `Hrule           -> "<hr/>"
    | `Raw raw         ->  pr_raw raw
    | `Verbatim s      -> sprintf"<tt>%s</tt>" s
    | `Content s       -> s
    in

  let rec print_rec_element = function
    | `Emphasis d      -> (sprintf "<i>%s</i>" (print_no_eval d))
    | `List lst        -> sprintf "<ul>%s</ul>"
      (print_with_sep "" (List.map print_no_eval lst))
    | `Seq lst -> print_with_sep "" (List.map print_no_eval lst)
    | `Item doc -> sprintf "<li>%s</li>" (print_no_eval doc)
    | _ -> raise Unhandled_case

  and print_no_eval = function
    | #Cst.flat_element as c -> print_flat_element c
    | #Cst.rec_element as c -> print_rec_element c
    |_ -> raise Unhandled_case in
    try Some
        (replace_newlines (print_no_eval cst))
    with Unhandled_case -> None

let pr_link link_type link =
  let normalize name = (List.nth name ((List.length name) -1)) in
  match link_type with
    | `Root ->
      sprintf "<a id=\"%s\">%s</a>" (normalize link.adress) link.content
    | `Link ->
        sprintf "<a href=\"#%s\">%s</a>" (normalize link.adress) link.content

let indent id_lvl =
  let str = "&nbsp;" and tab_size = 4 and ret = ref "" in
  if id_lvl = 0 then ""
  else
    begin
      for i = 1 to tab_size * id_lvl do
        ret := str ^ !ret
      done;
    !ret
    end

let code c =
  let rec aux = function
  Keyword s ->   sprintf "<span class=\"id\" type=\"keyword\">%s</span>" s
  | Ident s ->   sprintf "<span class=\"id\" type=\"var\">%s</span>" s
  | Literal s -> sprintf "<span class=\"id\" type=\"var\">%s</span>" s
  | Tactic s -> sprintf  "<span class=\"id\" type=\"inductive\">%s</span>" s
  | Symbol s -> sprintf "<span class=\"id\" type=\"lemma\">%s</span>" s
  | NoFormat s -> s
  | Root l -> pr_link `Root l
  | Link l -> pr_link `Link l
  | Output_command (raw,[]) -> pr_raw raw
  | Output_command (raw,args) -> print_with_sep (pr_raw raw) args
  | Indent (size,code) -> (indent size) ^ (aux code)
  in (List.map replace_newlines (List.map aux c))

let begindoc ()  = "<div class=\"doc\">"
let enddoc ()    = "</div>"
let begincode () = "<div class=\"code\">"
let endcode ()   = "</div>"

(* FIXME: make real function *)

let newline () = "<br />"

(*FIXME*)
let index lst =
  sprintf "<h1>Index of symbols</h1><br/>\n<hr/>\n<ul>\n%s</ul>\n"
    (String.concat "" (List.map (fun e -> sprintf "<li>%s</li>\n" (pr_link `Link
    e)) lst))

let file_index lst =
  sprintf "<h1>Index of files</h1><br/>\n<hr/>\n<ul>\n%s</ul>\n"
  (String.concat "" (List.map (fun (fname,modname) -> sprintf "<li><a href=\"%s\">%s</a></li>\n"
    fname modname) lst))

let footer () =
    "\n<hr/>\nThis page has been generated by " ^
	  "<a href=\"#\">coqdoc</a>\n"            ^
	  "</div>\n\n</div>\n\n</body>\n</html>"
